export interface RedditRespDataModel {
  approved_at_utc?: number | null;
  subreddit?: string | null;
  selftext?: string | null;
  author_fullname?: string | null;
  saved?: boolean;
  mod_reason_title?: null;
  gilded?: number;
  clicked?: boolean;
  title?: string | null;
  link_flair_richtext?: [];
  subreddit_name_prefixed?: string | null;
  hidden?: boolean;
  pwls?: number;
  link_flair_css_class?: string | null;
  downs?: number;
  thumbnail_height?: number;
  top_awarded_type?: null;
  hide_score?: boolean;
  name?: string | null;
  quarantine?: boolean;
  link_flair_text_color?: string | null;
  upvote_ratio?: number;
  author_flair_background_color?: null;
  subreddit_type?: string | null;
  ups?: number;
  total_awards_received?: number;
  media_embed?: {};
  thumbnail_width?: number;
  author_flair_template_id?: null;
  is_original_content?: boolean;
  user_reports?: [];
  secure_media?: null;
  is_reddit_media_domain?: boolean;
  is_meta?: boolean;
  category?: null;
  secure_media_embed?: {};
  link_flair_text?: null;
  can_mod_post?: boolean;
  score?: number;
  approved_by?: null;
  author_premium?: boolean;
  thumbnail?: string | null;
  edited?: boolean;
  author_flair_css_class?: null;
  author_flair_richtext?: [];
  gildings?: {};
  post_hint?: string | null;
  content_categories?: null;
  is_self?: boolean;
  mod_note?: null;
  created?: number;
  link_flair_type?: string | null;
  wls?: number;
  removed_by_category?: null;
  banned_by?: null;
  author_flair_type?: string | null;
  domain?: string | null;
  allow_live_comments?: boolean;
  selftext_html?: null;
  likes?: null;
  suggested_sort?: string | null;
  banned_at_utc?: null;
  view_count?: null;
  archived?: boolean;
  no_follow?: boolean;
  is_crosspostable?: boolean;
  pinned?: boolean;
  over_18?: boolean;
  preview?: {
    images?: [
      {
        source?: {
          url: string | null;
          width: number;
          height: number;
        };
        resolutions?: [
          {
            url?: string | null;
            width?: number;
            height?: number;
          },
        ];
        variants?: {};
        id?: string | null;
      },
    ];
    enabled?: boolean;
  };
  all_awardings?: [];
  awarders?: [];
  media_only?: boolean;
  can_gild?: boolean;
  spoiler?: boolean;
  locked?: boolean;
  author_flair_text?: null;
  treatment_tags?: [];
  visited?: boolean;
  removed_by?: null;
  num_reports?: null;
  distinguished?: null;
  subreddit_id?: string | null;
  mod_reason_by?: null;
  removal_reason?: null;
  link_flair_background_color?: string | null;
  id?: string | null;
  is_robot_indexable?: boolean;
  report_reasons?: null;
  author?: string | null;
  discussion_type?: null;
  num_comments?: number;
  send_replies?: boolean;
  whitelist_status?: string | null;
  contest_mode?: boolean;
  mod_reports?: [];
  author_patreon_flair?: boolean;
  author_flair_text_color?: null;
  permalink?: string | null;
  parent_whitelist_status?: string | null;
  stickied?: boolean;
  url?: string | null;
  subreddit_subscribers?: number;
  created_utc?: number;
  num_crossposts?: number;
  media?: null;
  is_video?: boolean;
}
