export const languages = [
  { key: 'ar', text: 'ARABIC', value: 'ar' },
  { key: 'de', text: 'GERMAN', value: 'de' },
  { key: 'en', text: 'ENGLISH', value: 'en' },
  { key: 'es', text: 'SPANISH', value: 'es' },
  { key: 'fr', text: 'FRENCH', value: 'fr' },
  { key: 'he', text: 'HEBREW', value: 'he' },
  { key: 'it', text: 'ITALIAN', value: 'it' },
  { key: 'nl', text: 'DUTCH', value: 'nl' },
  { key: 'no', text: 'NORWEGIAN', value: 'no' },
  { key: 'pt', text: 'PORTUGUESE', value: 'pt' },
  { key: 'ru', text: 'RUSSIAN', value: 'ru' },
  { key: 'se', text: 'NORTHERN SAMI', value: 'se' },
  { key: 'zh', text: 'CHINESE', value: 'zh' },
];
